<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ClienteSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('clientes')->insert([
            [
                'ruc' => '00000000000',
                'razon_social' => 'Cliente simple',
                'nombres' => '',
                'apellidos' => 'Cliente simple',
                'dni' => '00000000',
                'fecha_nacimiento' => null,
                'correo' => '',
                'celular' => '',
                'telefono' => '',
                'direccion' => '-',
                'nacionalidad' => 'peruano',
                'pais_origen' => 'Perú',
                'pasaporte' => '',
                'vigencia_pasaporte' => null,
                'tipo_visado' => 'ninguno',
                'valido_visa' => null,
                'vacunas' => null,
                'seguros' => null,
                'autorizacion_viaje' => 'no aplica',
                'archivos' => null,
                'activo' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ruc' => '20512345678',
                'razon_social' => 'Turismo Andino S.A.C.',
                'nombres' => 'Roberto',
                'apellidos' => 'Flores Quispe',
                'dni' => '45678912',
                'fecha_nacimiento' => '1985-03-15',
                'correo' => 'roberto.flores@gmail.com',
                'celular' => '951234567',
                'telefono' => '014523678',
                'direccion' => 'Av. Arequipa 1520, Lince, Lima',
                'nacionalidad' => 'peruano',
                'pais_origen' => 'Perú',
                'pasaporte' => 'PE45678912',
                'vigencia_pasaporte' => '2027-06-20',
                'tipo_visado' => 'turista',
                'valido_visa' => null,
                'vacunas' => json_encode([
                    ['certificado' => 'FA2024-001', 'fecha' => '2024-08-10'],
                    ['certificado' => 'FA2023-445', 'fecha' => '2023-12-01'],
                ]),
                'seguros' => json_encode([['seguro' => 'Rímac seguros - Plan Viajero Premium', 'fecha' => '2024-07-01']]),
                'autorizacion_viaje' => 'no aplica',

                'archivos' => null,
                'activo' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ruc' => null,
                'razon_social' => null,
                'nombres' => 'Sarah',
                'apellidos' => 'Johnson',
                'dni' => null,
                'fecha_nacimiento' => '1990-07-22',
                'correo' => 'sarah.johnson@outlook.com',
                'celular' => '987654321',
                'telefono' => null,
                'direccion' => null,
                'nacionalidad' => 'extranjero',
                'pais_origen' => 'Estados Unidos',
                'pasaporte' => 'US987654321',
                'vigencia_pasaporte' => '2028-01-15',
                'tipo_visado' => 'turista',
                'valido_visa' => null,
                'vacunas' => json_encode([['certificado' => 'US-YF-2025', 'fecha' => '2025-01-15']]),
                'seguros' => json_encode([['seguro' => 'World Nomads - Standard Plan', 'fecha' => '2025-02-01']]),
                'autorizacion_viaje' => 'no aplica',

                'archivos' => null,
                'activo' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ruc' => null,
                'razon_social' => null,
                'nombres' => 'Luis Alberto',
                'apellidos' => 'Vargas Medina',
                'dni' => '72345678',
                'fecha_nacimiento' => '1978-11-05',
                'correo' => 'luis.vargas@hotmail.com',
                'celular' => '965432178',
                'telefono' => '054234567',
                'direccion' => 'Calle Mercaderes 312, Arequipa',
                'nacionalidad' => 'peruano',
                'pais_origen' => 'Perú',
                'pasaporte' => null,
                'vigencia_pasaporte' => null,
                'tipo_visado' => 'turista',
                'valido_visa' => null,
                'vacunas' => null,
                'seguros' => null,
                'autorizacion_viaje' => 'no aplica',

                'archivos' => null,
                'activo' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ruc' => '20198765432',
                'razon_social' => 'Grupo Viajes del Sur E.I.R.L.',
                'nombres' => 'Carmen',
                'apellidos' => 'Torres Huamán',
                'dni' => '31234567',
                'fecha_nacimiento' => '1982-05-18',
                'correo' => 'carmen.torres@viajesdelsur.pe',
                'celular' => '943218765',
                'telefono' => '084256789',
                'direccion' => 'Av. El Sol 456, Cusco',
                'nacionalidad' => 'peruano',
                'pais_origen' => 'Perú',
                'pasaporte' => 'PE31234567',
                'vigencia_pasaporte' => '2026-09-30',
                'tipo_visado' => 'trabajo',
                'valido_visa' => '2026-12-31',
                'vacunas' => json_encode([['certificado' => 'FA2023-445', 'fecha' => '2023-12-01']]),
                'seguros' => json_encode([['seguro' => 'Pacífico seguros - Viajero Plus', 'fecha' => '2023-11-15']]),
                'autorizacion_viaje' => 'no aplica',

                'archivos' => null,
                'activo' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ruc' => null,
                'razon_social' => null,
                'nombres' => 'Pedro',
                'apellidos' => 'Castillo Ramos',
                'dni' => '87654321',
                'fecha_nacimiento' => '2010-02-14',
                'correo' => null,
                'celular' => '912345678',
                'telefono' => null,
                'direccion' => 'Jr. Junín 890, Huancayo',
                'nacionalidad' => 'peruano',
                'pais_origen' => 'Perú',
                'pasaporte' => null,
                'vigencia_pasaporte' => null,
                'tipo_visado' => 'turista',
                'valido_visa' => null,
                'vacunas' => json_encode([['certificado' => 'FA2024-789', 'fecha' => '2024-03-20']]),
                'seguros' => null,
                'autorizacion_viaje' => 'si',
                'archivos' => null,
                'activo' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
