<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ClienteSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('clientes')->insert([
            [
                'ruc' => '20512345678',
                'razon_social' => 'Turismo Andino S.A.C.',
                'nombres' => 'Roberto',
                'apellidos' => 'Flores Quispe',
                'dni' => '45678912',
                'carnet_extranjeria' => null,
                'fecha_nacimiento' => '1985-03-15',
                'correo' => 'roberto.flores@gmail.com',
                'celular' => '951234567',
                'telefono' => '014523678',
                'direccion' => 'Av. Arequipa 1520, Lince, Lima',
                'nacionalidad' => 'Peruana',
                'pais_origen' => 'Perú',
                'pasaporte' => true,
                'vigencia_pasaporte' => '2027-06-20',
                'visado' => false,
                'valido_visa' => null,
                'vacunacion' => true,
                'vacunacion_fiebre_amarilla' => json_encode(['certificado' => 'FA2024-001', 'fecha' => '2024-08-10']),
                'tiene_seguro' => true,
                'seguro' => 'Rímac Seguros - Plan Viajero Premium',
                'autorizacion_viaje' => 'no aplica',
                'pasaporte_permanente' => 'PE45678912',
                'pais_residencia' => 'Perú',
                'archivos' => null,
                'activo' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ruc' => null,
                'razon_social' => null,
                'nombres' => 'Sarah',
                'apellidos' => 'Johnson',
                'dni' => null,
                'carnet_extranjeria' => 'CE001234567890',
                'fecha_nacimiento' => '1990-07-22',
                'correo' => 'sarah.johnson@outlook.com',
                'celular' => '987654321',
                'telefono' => null,
                'direccion' => null,
                'nacionalidad' => 'Estadounidense',
                'pais_origen' => 'Estados Unidos',
                'pasaporte' => true,
                'vigencia_pasaporte' => '2028-01-15',
                'visado' => false,
                'valido_visa' => null,
                'vacunacion' => true,
                'vacunacion_fiebre_amarilla' => json_encode(['certificado' => 'US-YF-2025', 'fecha' => '2025-01-15']),
                'tiene_seguro' => true,
                'seguro' => 'World Nomads - Standard Plan',
                'autorizacion_viaje' => 'no aplica',
                'pasaporte_permanente' => 'US987654321',
                'pais_residencia' => 'Estados Unidos',
                'archivos' => null,
                'activo' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ruc' => null,
                'razon_social' => null,
                'nombres' => 'Luis Alberto',
                'apellidos' => 'Vargas Medina',
                'dni' => '72345678',
                'carnet_extranjeria' => null,
                'fecha_nacimiento' => '1978-11-05',
                'correo' => 'luis.vargas@hotmail.com',
                'celular' => '965432178',
                'telefono' => '054234567',
                'direccion' => 'Calle Mercaderes 312, Arequipa',
                'nacionalidad' => 'Peruana',
                'pais_origen' => 'Perú',
                'pasaporte' => false,
                'vigencia_pasaporte' => null,
                'visado' => false,
                'valido_visa' => null,
                'vacunacion' => false,
                'vacunacion_fiebre_amarilla' => null,
                'tiene_seguro' => false,
                'seguro' => null,
                'autorizacion_viaje' => 'no aplica',
                'pasaporte_permanente' => null,
                'pais_residencia' => 'Perú',
                'archivos' => null,
                'activo' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ruc' => '20198765432',
                'razon_social' => 'Grupo Viajes del Sur E.I.R.L.',
                'nombres' => 'Carmen',
                'apellidos' => 'Torres Huamán',
                'dni' => '31234567',
                'carnet_extranjeria' => null,
                'fecha_nacimiento' => '1982-05-18',
                'correo' => 'carmen.torres@viajesdelsur.pe',
                'celular' => '943218765',
                'telefono' => '084256789',
                'direccion' => 'Av. El Sol 456, Cusco',
                'nacionalidad' => 'Peruana',
                'pais_origen' => 'Perú',
                'pasaporte' => true,
                'vigencia_pasaporte' => '2026-09-30',
                'visado' => true,
                'valido_visa' => '2026-12-31',
                'vacunacion' => true,
                'vacunacion_fiebre_amarilla' => json_encode(['certificado' => 'FA2023-445', 'fecha' => '2023-12-01']),
                'tiene_seguro' => true,
                'seguro' => 'Pacífico Seguros - Viajero Plus',
                'autorizacion_viaje' => 'no aplica',
                'pasaporte_permanente' => 'PE31234567',
                'pais_residencia' => 'Perú',
                'archivos' => null,
                'activo' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ruc' => null,
                'razon_social' => null,
                'nombres' => 'Pedro',
                'apellidos' => 'Castillo Ramos',
                'dni' => '87654321',
                'carnet_extranjeria' => null,
                'fecha_nacimiento' => '2010-02-14',
                'correo' => null,
                'celular' => '912345678',
                'telefono' => null,
                'direccion' => 'Jr. Junín 890, Huancayo',
                'nacionalidad' => 'Peruana',
                'pais_origen' => 'Perú',
                'pasaporte' => false,
                'vigencia_pasaporte' => null,
                'visado' => false,
                'valido_visa' => null,
                'vacunacion' => true,
                'vacunacion_fiebre_amarilla' => json_encode(['certificado' => 'FA2024-789', 'fecha' => '2024-03-20']),
                'tiene_seguro' => false,
                'seguro' => null,
                'autorizacion_viaje' => 'si',
                'pasaporte_permanente' => null,
                'pais_residencia' => 'Perú',
                'archivos' => null,
                'activo' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
