<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class VentaVueloTramoSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('venta_vuelos_tramos')->insert([
            // Venta vuelo 1: Lima → Cusco (ida)
            [
                'venta_vuelo_id' => 1,
                'origen' => 'Lima (LIM)',
                'destino' => 'Cusco (CUZ)',
                'fecha' => '2026-03-28',
                'pasajeros' => 2,
                'equipaje' => '2 maletas 23kg + 2 carry-on',
                'precio_soles' => 450.00,
                'precio_dolares' => 120.00,
                'costo_soles' => 320.00,
                'costo_dolares' => 85.00,
                'codigo_vuelo' => 'LA2040',
                'aerolinea' => 'LATAM Airlines',
                'numero_vuelo' => '2040',
                'aeronave' => 'Airbus A320',
                'fecha_salida' => '2026-03-28 06:30:00',
                'fecha_llegada' => '2026-03-28 07:45:00',
                'hora_salida' => '06:30:00',
                'horario_llegada' => '07:45:00',
                'duracion_minutos' => 75,
                'terminal_salida' => '2',
                'puerta_embarque' => '15B',
                'terminal_llegada' => '1',
                'estado_tramo' => 'confirmado',
                'localizador' => 'XK4F2D',
                'billete_electronico' => '045-2345678901',
                'asientos_asignados' => '12A,12B',
                'clase_vuelo' => 'economica',
                'escala' => false,
                'numero_escala' => 0,
                'observaciones' => null,
                'activo' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // Venta vuelo 1: Cusco → Lima (vuelta)
            [
                'venta_vuelo_id' => 1,
                'origen' => 'Cusco (CUZ)',
                'destino' => 'Lima (LIM)',
                'fecha' => '2026-04-01',
                'pasajeros' => 2,
                'equipaje' => '2 maletas 23kg + 2 carry-on',
                'precio_soles' => 400.00,
                'precio_dolares' => 107.00,
                'costo_soles' => 290.00,
                'costo_dolares' => 77.00,
                'codigo_vuelo' => 'LA2041',
                'aerolinea' => 'LATAM Airlines',
                'numero_vuelo' => '2041',
                'aeronave' => 'Airbus A320',
                'fecha_salida' => '2026-04-01 18:00:00',
                'fecha_llegada' => '2026-04-01 19:15:00',
                'hora_salida' => '18:00:00',
                'horario_llegada' => '19:15:00',
                'duracion_minutos' => 75,
                'terminal_salida' => '1',
                'puerta_embarque' => null,
                'terminal_llegada' => '2',
                'estado_tramo' => 'pendiente',
                'localizador' => 'XK4F2D',
                'billete_electronico' => '045-2345678902',
                'asientos_asignados' => null,
                'clase_vuelo' => 'economica',
                'escala' => false,
                'numero_escala' => 0,
                'observaciones' => 'Vuelo de retorno',
                'activo' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // Venta vuelo 2: Lima → Cusco
            [
                'venta_vuelo_id' => 2,
                'origen' => 'Lima (LIM)',
                'destino' => 'Cusco (CUZ)',
                'fecha' => '2026-04-05',
                'pasajeros' => 1,
                'equipaje' => '1 maleta 23kg + 1 carry-on',
                'precio_soles' => 380.00,
                'precio_dolares' => 101.00,
                'costo_soles' => 270.00,
                'costo_dolares' => 72.00,
                'codigo_vuelo' => 'H8 321',
                'aerolinea' => 'Sky Airline',
                'numero_vuelo' => '321',
                'aeronave' => 'Airbus A320neo',
                'fecha_salida' => '2026-04-05 08:00:00',
                'fecha_llegada' => '2026-04-05 09:20:00',
                'hora_salida' => '08:00:00',
                'horario_llegada' => '09:20:00',
                'duracion_minutos' => 80,
                'terminal_salida' => '1',
                'puerta_embarque' => '8A',
                'terminal_llegada' => '1',
                'estado_tramo' => 'emitido',
                'localizador' => 'MN7B3K',
                'billete_electronico' => '180-9876543210',
                'asientos_asignados' => '5F',
                'clase_vuelo' => 'economica_plus',
                'escala' => false,
                'numero_escala' => 0,
                'observaciones' => 'Pasajera pide asiento ventana',
                'activo' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
