<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class VentaSeeder extends Seeder
{
	public function run(): void
	{
		DB::table('ventas')->insert([
			[
				'usuario_id' => 1,
				'cliente_id' => 1,
				'fecha' => '2026-03-21',
				'estado_pago' => 'pendiente',
				'personas' => 3,
				'precio' => 1250,
				'adelanto' => 0,
				'costo' => 1000,
				'descuento' => 0,
				'motivo_descuento' => null,
				'departamento_id' => 15, // Lima
				'ciudad' => 'Lima',
				'nivel' => 1,
				'estado' => 'activo',
				'progreso' => 'venta',
				'nacionalidad' => 'peruana',
				'autorizaciones' => '{}',
				'activo' => true,
				'created_at' => now(),
				'updated_at' => now(),
			],
			[
				'usuario_id' => 2,
				'cliente_id' => 2,
				'fecha' => '2026-03-20',
				'estado_pago' => 'completo',
				'personas' => 2,
				'precio' => 2350,
				'adelanto' => 0,
				'costo' => 2000,
				'descuento' => 50,
				'motivo_descuento' => 'Promoción marzo',
				'departamento_id' => 4, // Arequipa
				'ciudad' => 'Arequipa',
				'nivel' => 1,
				'estado' => 'activo',
				'progreso' => 'venta',
				'nacionalidad' => 'extranjera',
				'autorizaciones' => '{}',
				'activo' => true,
				'created_at' => now(),
				'updated_at' => now(),
			],
			[
				'usuario_id' => 3,
				'cliente_id' => 3,
				'fecha' => '2026-03-19',
				'estado_pago' => 'pendiente',
				'personas' => 3,
				'precio' => 400,
				'adelanto' => 0,
				'costo' => 300,
				'descuento' => 0,
				'motivo_descuento' => null,
				'departamento_id' => 9,
				'ciudad' => 'Acoria',
				'nivel' => 1,
				'estado' => 'activo',
				'progreso' => 'cotización',
				'nacionalidad' => 'peruana',
				'autorizaciones' => '{}',
				'activo' => true,
				'created_at' => now(),
				'updated_at' => now(),
			],
			[
				'usuario_id' => 4,
				'cliente_id' => 4,
				'fecha' => '2026-03-18',
				'estado_pago' => 'adelantado',
				'personas' => 1,
				'precio' => 1800,
				'adelanto' => 500,
				'costo' => 1500,
				'descuento' => 100,
				'motivo_descuento' => 'Cliente frecuente',
				'departamento_id' => 20, // Piura
				'ciudad' => 'Piura',
				'nivel' => 1,
				'estado' => 'activo',
				'progreso' => 'venta',
				'nacionalidad' => 'peruana',
				'autorizaciones' => '{}',
				'activo' => true,
				'created_at' => now(),
				'updated_at' => now(),
			],
			[
				'usuario_id' => 1,
				'cliente_id' => 1,
				'fecha' => '2026-03-15',
				'estado_pago' => 'anulado',
				'personas' => 0,
				'precio' => 0,
				'adelanto' => 0,
				'costo' => 0,
				'descuento' => 0,
				'motivo_descuento' => null,
				'departamento_id' => 1, // Amazonas
				'ciudad' => 'Chachapoyas',
				'nivel' => 1,
				'estado' => 'anulado',
				'progreso' => 'venta',
				'nacionalidad' => 'peruana',
				'autorizaciones' => '{}',
				'activo' => true,
				'created_at' => now(),
				'updated_at' => now(),
			],
		]);
	}
}
